stages:
  train_model:
    cmd: set MLFLOW_TRACKING_USERNAME=franciskyalo && set MLFLOW_TRACKING_PASSWORD=1a78b581682c72dfc2cea4f670528d642b94cf2b && python model/train.py
    deps:
      - model/train.py
    outs:
      - model/model.pkl

  deployfastapi_model:
    cmd: python app/main.py
    deps:
      - model/model.pkl
